insert into `province` (`id`, `province_code`, `province_name`) values('1','SD','山东');
insert into `province` (`id`, `province_code`, `province_name`) values('2','SX','山西');
insert into `province` (`id`, `province_code`, `province_name`) values('3','HN','河南');
insert into `province` (`id`, `province_code`, `province_name`) values('4','HB','河北');
insert into `province` (`id`, `province_code`, `province_name`) values('5','GD','广东');
insert into `province` (`id`, `province_code`, `province_name`) values('6','GX','广西');
insert into `province` (`id`, `province_code`, `province_name`) values('7','JS','江苏');
insert into `province` (`id`, `province_code`, `province_name`) values('8','JX','江西');
insert into `province` (`id`, `province_code`, `province_name`) values('9','SC','四川');
insert into `province` (`id`, `province_code`, `province_name`) values('10','FJ','福建');
insert into `province` (`id`, `province_code`, `province_name`) values('11','GS','甘肃');
insert into `province` (`id`, `province_code`, `province_name`) values('12','JL','吉林');
insert into `province` (`id`, `province_code`, `province_name`) values('13','LN','辽宁');
insert into `province` (`id`, `province_code`, `province_name`) values('14','NX','宁夏');
insert into `province` (`id`, `province_code`, `province_name`) values('15','QH','青海');

insert into `city` (`id`, `city_name`, `p_id`, `size`) values('1','济南','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('2','青岛','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('3','烟台','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('4','威海','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('5','济宁','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('6','潍坊','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('7','淄博','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('8','聊城','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('9','临沂','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('10','菏泽','1','BIG');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('11','日照','1','SMALL');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('12','泰安','1','SMALL');
insert into `city` (`id`, `city_name`, `p_id`, `size`) values('13','test','1','SMALL');